### ISSUE TITLE
Each time return 255 after successfull work

### ISSUE THREAD

**Issue by DruKot** [vanhauser-thc/thc-hydra#279]
In the previous version of Hydra (8.1), when the brute-force task was successfully completed, Hydra returned an error code 0. In the latest version of Hydra (8.7), if the password is successfully matched, Hydra returns an error code of 255 instead of 0. Is this a bug?

For example:

_~#hydra -l ftp -p ftp ftp://192.168.5.1
....
[21][ftp] host: 192.168.5.1 login: ftp password: ftp
1 of 1 target successfully completed, 1 valid password found
Hydra (http...) finished at ...
~#echo $?
255
~#_

**Comment by DruKot** [comment]
This helped me:

_hydra.c:4103
-- if (error || j || exit_condition < 0)
++ if (error || !j || exit_condition < 0)_

But I'm not sure if this is the right solution

**Comment by vanhauser-thc** [comment]
Hi Drukot,

you are correct, I fixed it.
thanks!

**Comment by DruKot** [comment]
Ok..
was in 8.6:
` if (error || j || exit_condition < 0)`
now in 8.7-dev:
` if (error || j != 0 || exit_condition < 0)`

but is the same! (j) == (j != 0)

error still exist:
~# hydra -l ftp -p 123 ftp://192.168.5.214
Hydra v8.7-dev (c) 2018 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

```
Hydra (http://www.thc.org/thc-hydra) starting at 2018-04-25 10:36:16
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:0), ~1 try per task
[DATA] attacking ftp://192.168.5.214:21/
[21][ftp] host: 192.168.5.214   login: ftp   password: 123
1 of 1 target successfully completed, 1 valid password found
Hydra (http://www.thc.org/thc-hydra) finished at 2018-04-25 10:36:17
~# echo $?
255
```

With my fix all work correctly...

**Comment by vanhauser-thc** [comment]
j == 0 was correct, the bug was elsewhere
